oblicity/contracts/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
        from django.conf.urls.defaults import *

from . import views
from .views import ContractWizard

urlpatterns = patterns('',
                       url(r'^new/$', ContractWizard.as_view(), name='new_contract'),
                       url(r'^(?P<id>[0-9]+)/raw_template', views.get_template_content, name='get_template' ),
                       url(r'^(?P<id>[0-9]+)/edited_content', views.get_edited_content, name='get_contract_body' ),
                       url(r'^(?P<id>[0-9]+)/delete', views.delete_contract, name='delete_contract' ),
                       url(r'^(?P<id>[0-9]+)/edit', views.edit_contract, name='edit_contract' ),
                       )

oblicity/frontend/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
        from django.conf.urls.defaults import *

from . import views
from .views import SignIn, SignUp

urlpatterns = patterns('',
                       url(r'^signin/$', SignIn.as_view(), name='signin'),
                       url(r'^signup/$', SignUp.as_view(), name='signup'),
                       url(r'^signout/$', views.signout, name='signout'),
                       url(r'^resetpass/$', views.reset_password, name='resetpass'),
                       url(r'^profile/$', views.profile, name='profile'),
                        url(r'^contracts/', include('contracts.urls')),
                       url(r'^assets/$', views.assets_list, name='assets_list'),

                       )

oblicity/contracts/models.py
from django.db import models
from django.utils.translation import ugettext as _
from ckeditor.fields import RichTextField
from model_utils.models import TimeStampedModel
from django.contrib.auth.models import User






class ContractTemplate(models.Model):
    class Meta:
            verbose_name = _("Contract Template")
            verbose_name_plural = _("Contract Templates")

    name = models.CharField(max_length=64, help_text=_("Template name"), verbose_name=_("Template name"),unique=True )
    content = RichTextField(help_text=_("Template content"), verbose_name=_("Template content"))

    def __str__(self):
        return self.name

    def get_content(self):
        return self.content

class Contract(TimeStampedModel):

    DRAFT = 'draft'
    PENDING = 'pending'
    FUTURE = 'future'
    PRIVATE = 'private'
    PUBLISHED = 'published'

    STATUS_CHOICES = (
        (DRAFT, _("Draft")),
        (PENDING, _("Pending")),
        (FUTURE, _("Future")),
        (PRIVATE, _("Private")),
        (PUBLISHED, _("Published")),
            )

    class Meta:
        verbose_name = _("Contract")
        verbose_name_plural = _("Contracts")

    def __str__(self):
        return self.name

    name = models.CharField(max_length=64, help_text=_("Template name"), verbose_name=_("Template name"))
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=DRAFT)
    template = models.ForeignKey(to=ContractTemplate, help_text = _("The template this contract is based on"), verbose_name = _("Source template"))
    filled_template = RichTextField(help_text = _("The template filled with content, before editing"), verbose_name = _("Unedited body"))
    edited_template = RichTextField(help_text = _("Body of the text as to last edit."), verbose_name = _("Edited body"))
    owners = models.ManyToManyField(User, help_text = _("Owners of this contract, can make modifications."), verbose_name = _("Owners"))
    valid_from = models.DateField(help_text = _("FROM date of validity for this contract"), verbose_name = _("Valid from") )
    valid_to = models.DateField(help_text = _("TO date of validity for this contract"), verbose_name = _("Valid to"))
    last_editor = models.ForeignKey(User, help_text=_("The user who last edited this contract"), verbose_name=_("Last edited by"), related_name="last_contract")

oblicity/contracts/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextField
from django.utils.translation import ugettext as _
from .models import ContractTemplate, Contract
import autocomplete_light
from django.contrib.auth.models import User



class ContractWizard1(forms.Form):
    template = forms.ChoiceField(choices=[],label=_("Template:"))

    def __init__(self, *args, **kwargs):
        super(ContractWizard1, self).__init__(*args, **kwargs)
        self.fields['template'].choices= [(x.pk, x.name) for x in ContractTemplate.objects.all()]

class ContractWizard2(forms.Form):
    body = forms.CharField(widget=forms.widgets.HiddenInput())


class ContractWizard3(forms.Form):
    body_edited = forms.CharField(widget=CKEditorWidget(attrs={'class':'form-control'}))

class ContractWizard4(forms.Form):
    #owners = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Owners'}), label=_("Contract owners"))
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}), label=_("Contract title:"))
    status = forms.ChoiceField(choices=Contract.STATUS_CHOICES, label=_("Status:"))
    owners = autocomplete_light.MultipleChoiceField('UserProfileAutocomplete', label=_("Additional owners:"), required=False)
    notify_owners = forms.BooleanField(widget=forms.widgets.CheckboxInput(), label=_("Notify owners upon creation"),required=False, initial=True)
    valid_from = forms.DateField(widget=forms.widgets.DateInput(), label=_("Valid from:"))
    valid_to = forms.DateField(widget=forms.widgets.DateInput(), label=_("Valid to:"))


class EditContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ['name', 'status', 'edited_template', 'valid_from', 'valid_to' ]

oblicity/contracts/views.py
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, QueryDict, JsonResponse
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
import logging
from django.template import RequestContext
from django.conf import settings
from formtools.wizard.views import SessionWizardView
from .models import ContractTemplate, Contract
from django.shortcuts import get_object_or_404
import datetime
from profiles.models import UserProfile
from django.views.decorators.http import require_POST
from .forms import ContractWizard3,ContractWizard4, ContractWizard1, ContractWizard2, EditContractForm





logger = logging.getLogger('django')

WIZARD_STEP_0 = '0'
WIZARD_STEP_1 = '1'
WIZARD_STEP_2 = '2'
WIZARD_STEP_3 = '3'
WIZARD_STEP_4 = '4'

CONTRACT_WIZARD_TEMPLATES = { "0" : "contracts/contractwizard/new_contract_0.html",
                             "1" : "contracts/contractwizard/new_contract_1.html",
                             "2" : "contracts/contractwizard/new_contract_2.html",
                             "3" : "contracts/contractwizard/new_contract_3.html",
                             }

# Wizard for creating new contracts
class ContractWizard(SessionWizardView):
    form_list = [ContractWizard1, ContractWizard2, ContractWizard3, ContractWizard4]

    def get_template_names(self):
        return [CONTRACT_WIZARD_TEMPLATES[self.steps.current]]

    def done(self, form_list, **kwargs):
        logger.info(self.get_cleaned_data_for_step(WIZARD_STEP_3)['owners'] )
        contract = Contract()
        contract.name = self.get_cleaned_data_for_step(WIZARD_STEP_3)['title']
        contract.template = ContractTemplate.objects.get(pk=self.get_cleaned_data_for_step(WIZARD_STEP_0)['template'])
        contract.filled_template = self.get_cleaned_data_for_step(WIZARD_STEP_1)['body']
        contract.edited_template =  self.get_cleaned_data_for_step(WIZARD_STEP_2)['body_edited']
        contract.status = self.get_cleaned_data_for_step(WIZARD_STEP_3)['status']
        contract.valid_from = contract.valid_to = datetime.date.today()
        contract.last_editor = self.request.user
        contract.save()
        contract.owners.add(self.request.user)
        for profile_id in self.get_cleaned_data_for_step(WIZARD_STEP_3)['owners']:
            prof = UserProfile.objects.get(pk=profile_id)
            if not prof.owner in contract.owners.all():
                contract.owners.add(prof.owner)

        # contract.owners = []
        contract.valid_from = self.get_cleaned_data_for_step(WIZARD_STEP_3)['valid_from']
        contract.valid_to = self.get_cleaned_data_for_step(WIZARD_STEP_3)['valid_to']
        contract.save()
        messages.info(self.request, _("The contract has been modified successfully."))
        return redirect('assets_list')

    # Returns template and other information as context variables available on
    # the views, in order to correctly render templates
    def get_context_data(self, form, **kwargs):
        context = super(ContractWizard, self).get_context_data(form=form, **kwargs)
        if self.steps.current == WIZARD_STEP_1:
            template = ContractTemplate.objects.get(pk=self.get_cleaned_data_for_step(self.steps.prev)['template'])
            logger.info(self.get_cleaned_data_for_step(self.steps.prev)['template'])
            context.update({'template_content': template.get_content() })
        return context

    def get_form_initial(self, step):
        if step == WIZARD_STEP_2:
            return { 'body_edited' : self.get_cleaned_data_for_step(WIZARD_STEP_1)['body'] }

        if step == WIZARD_STEP_3:
            return { 'valid_from' : datetime.date.today().strftime("%m/%d/%Y")  }
        return self.initial_dict.get(step, {})



    # Overrides the class default method to inject data at certain steps
    def get_form(self, step=None, data=None, files=None):
        form = super(ContractWizard, self).get_form(step, data, files)

        if step is None:
            step = self.steps.current

        return form



def process_form_data(form_list):
    form_data = [form.cleaned_data for form in form_list]
    return form_data


# this view returns the raw content of a template, specified by the id GET
# parameter
def get_template_content(request,id):
    template = get_object_or_404(ContractTemplate,pk=id)
    return HttpResponse(template.get_content())

def get_edited_content(request,id):
    contract = get_object_or_404(Contract, pk=id)
    if not request.user in contract.owners.all():
        response = HttpResponse
        response.status_code = 401
        response.content =  _("Only owners of a contract may view its content")
        return response
    return HttpResponse(contract.edited_template)

# Delete contract is a POST only method
@require_POST
def delete_contract(request,id):
    response = HttpResponse()
    contract = get_object_or_404(Contract,pk=id)
    if request.user not in contract.owners.all():
        response.status_code = 401
        response.content = _("A user must be the owner of a contract in order to delete it")
        return response

    contract.owners.remove(request.user)
    response.status_code = 200
    messages.success( request, _("The contract "+contract.name+" has been successfully deleted"))
    return response


def edit_contract(request, id):

    contract = get_object_or_404(Contract, pk=id)
    logger.info(contract.owners)

    # If the method is POST, it received a form submission
    if request.method == 'POST':
        form = EditContractForm(request.POST, instance=contract)
        if form.is_valid():
            form.instance.last_editor = request.user
            form.save()
            logger.info(request.user.username+" successfully edited contract ID"+ str(contract.id))
            messages.success(request, "The contract "+contract.name+" was successfully saved.")
            return redirect("assets_list")
    else:
        form = EditContractForm(instance=contract)

    return render_to_response('contracts/edit_contract.html', {'form': form }, context_instance = RequestContext(request))

oblicity/templates/contracts/edit_contract.html
{% extends 'frontend/main.html' %}
{%  load staticfiles %}
{% load thumbnail %}
{% load i18n %}


{% block extrahead %}
{% endblock %}

<!-- Start: Content -->
  {% block app_content %}
    <section id="content_wrapper">
        <div id="topbar">
        <div class="topbar-left">
            <ol class="breadcrumb">
                <li class="crumb-active"><a href="#">{{ request.user.first_name }}{% trans "'s dashboard'" %}</a></li>
                <li class="crumb-trail">{% trans "Assets list" %}</li>
                <li class="crumb-trail">{% trans "Edit Contract nr." %}{{ form.instance.id }}</li>
            </ol>
        </div>
        </div>
        <div id="content" class="prn">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel" >
                        <div class="panel-heading panel-visible">
                            <span class="panel-title">
                                <span class="fa fa-edit"></span>
                                {% trans "Edit" %}
                            </span>
                        </div>
                        <div class="panel-body">
                            {% block panel_content %}
                                <form action="{% url "edit_contract" id=form.instance.id %}" method="post" class="form-horizontal" >{% csrf_token %}
                                    {{ form.media }}

                                    <p>Here you and the other owners can make modifications to this contract. All changes will be made final once you press the Save Changes button.</p>
                                    <hr>
                                    
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">{{ form.name.label }}</label>
                                        <div class ="col-md-9">
                                            {{ form.name }}
                                        </div>
                                    {{ form.name.errors }}
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">{{ form.status.label }}</label>
                                        <div class ="col-md-9">
                                            {{ form.status }}
                                        </div>
                                    {{ form.status.errors }}
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">{{ form.valid_from.label }}</label>
                                        <div class ="col-md-9">
                                            {{ form.valid_from }}
                                        </div>
                                    {{ form.valid_from.errors }}
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">{{ form.valid_to.label }}</label>
                                        <div class ="col-md-9">
                                            {{ form.valid_to }}
                                        </div>
                                    {{ form.valid_to.errors }}
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">{{ form.edited_template.label }}</label>
                                        <div class ="col-md-9">
                                            {{ form.edited_template }}
                                            {{ form.edited_template.errors }}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label"></label>
                                        <div class ="col-md-9">
                                            <button class="btn bg-purple2 btn-lg " type="submit"><span class="fa fa-save"></span> {% trans "Save Changes" %}</button>
                                        </div>
                                    </div>



                                </form> 
                            {% endblock %}
                        </div>
                    </div>  
                </div>
                </div>
        </div>

    </section>
    {% endblock %}
  <!-- End: Content --> 

{% block extrascripts %}
        <script type="text/javascript">
            jQuery(document).ready(function () {
                $("#id_valid_from").datepicker()
                $("#id_valid_to").datepicker()
                $('#id_status').multiselect();
               
            });
        </script>
        <!-- Needed for autocomplete-light package -->
        {% include 'autocomplete_light/static.html' %}
{% endblock %}