oblicity/frontend/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
        from django.conf.urls.defaults import *

from . import views
from .views import SignIn, SignUp

urlpatterns = patterns('',
                       url(r'^signin/$', SignIn.as_view(), name='signin'),
                       url(r'^signup/$', SignUp.as_view(), name='signup'),
                       url(r'^signout/$', views.signout, name='signout'),
                       url(r'^resetpass/$', views.reset_password, name='resetpass'),
                       url(r'^profile/$', views.profile, name='profile'),
                        url(r'^contracts/', include('contracts.urls')),
                       url(r'^assets/$', views.assets_list, name='assets_list'),

                       )

oblicity/contracts/models.py
from django.db import models
from django.utils.translation import ugettext as _
from ckeditor.fields import RichTextField
from model_utils.models import TimeStampedModel
from django.contrib.auth.models import User






class ContractTemplate(models.Model):
    class Meta:
            verbose_name = _("Contract Template")
            verbose_name_plural = _("Contract Templates")

    name = models.CharField(max_length=64, help_text=_("Template name"), verbose_name=_("Template name"),unique=True )
    content = RichTextField(help_text=_("Template content"), verbose_name=_("Template content"))

    def __str__(self):
        return self.name

    def get_content(self):
        return self.content

class Contract(TimeStampedModel):

    DRAFT = 'draft'
    PENDING = 'pending'
    FUTURE = 'future'
    PRIVATE = 'private'
    PUBLISHED = 'published'

    STATUS_CHOICES = (
        (DRAFT, _("Draft")),
        (PENDING, _("Pending")),
        (FUTURE, _("Future")),
        (PRIVATE, _("Private")),
        (PUBLISHED, _("Published")),
            )

    class Meta:
        verbose_name = _("Contract")
        verbose_name_plural = _("Contracts")

    def __str__(self):
        return self.name

    name = models.CharField(max_length=64, help_text=_("Template name"), verbose_name=_("Template name"))
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=DRAFT)
    template = models.ForeignKey(to=ContractTemplate, help_text = _("The template this contract is based on"), verbose_name = _("Source template"))
    filled_template = RichTextField(help_text = _("The template filled with content, before editing"), verbose_name = _("Unedited body"))
    edited_template = RichTextField(help_text = _("Body of the text as to last edit."), verbose_name = _("Edited body"))
    owners = models.ManyToManyField(User, help_text = _("Owners of this contract, can make modifications."), verbose_name = _("Owners"))
    valid_from = models.DateField(help_text = _("FROM date of validity for this contract"), verbose_name = _("Valid from") )
    valid_to = models.DateField(help_text = _("TO date of validity for this contract"), verbose_name = _("Valid to"))
    last_editor = models.ForeignKey(User, help_text=_("The user who last edited this contract"), verbose_name=_("Last edited by"), related_name="last_contract")

oblicity/frontend/models.py
from django.db import models

# Create your models here.

oblicity/profiles/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from sorl.thumbnail import ImageField, get_thumbnail
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
import os
from django.conf import settings

class UserProfile(TimeStampedModel):
    class Meta:
            verbose_name = _("User Profile")
            verbose_name_plural = _("User Profiles")

    owner = models.ForeignKey(User, help_text=("User associated to this profile"), verbose_name=_("Owner"))
    birth = models.DateField(verbose_name=_("Birth date"), help_text=_("Birth date"), null=True, blank=True)
    profession = models.CharField(max_length=64, help_text=_("Profession"), verbose_name=_("Profession"), null=True, blank=True)
    phone = models.CharField(max_length=64, help_text=_("Phone"), verbose_name=_("Phone"), null=True, blank=True)
    address = models.CharField(max_length=64, help_text=_("Address"), verbose_name=_("Address"), null=True, blank=True)
    idcard = models.CharField(max_length=64, help_text=_("ID Number"), verbose_name=_("ID Card Number"), null=True, blank=True)
    website = models.URLField(help_text=_("Website"), verbose_name=_("Website"), null=True, blank=True)
    description = models.TextField(max_length=512, help_text=_("Description"), verbose_name=_("Brief personal description"), null=True, blank=True)
    picture = ImageField(help_text=_("Profile picture"), upload_to="profilepictures", verbose_name=_("Profile picture")  )


    def __str__(self):
        return self.owner.username+ _("'s profile")

oblicity/frontend/views.py
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, QueryDict, JsonResponse
from django.views.generic import View
from django.views.generic.base import TemplateView
from profiles.forms import LoginForm, SignUpForm, PasswordResetForm, ProfileUpdateForm
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
import logging
from django.template import RequestContext
from profiles.models import UserProfile
import os
from django.conf import settings
from formtools.wizard.views import SessionWizardView

from contracts.models import Contract, ContractTemplate


# Imports the logger and makes it available to all views
logger = logging.getLogger('django')






# SignIn is implemented as Class Based View because, why not
class SignIn(View):
    form_class = LoginForm
    template_name = "frontend/signin.html"

    def get(self, request):
        form  = self.form_class()
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = LoginForm(request.POST)
        # If the login form validates correctly
        if form.is_valid():
            usr = form.cleaned_data['username']
            pwd = form.cleaned_data['password']
            # Attempts autentication
            user = authenticate(username=usr,
                                password=pwd)
            # If the user is authenticated using the supplied credentials
            if user:
                if user.is_active:
                    login(request, user)
                    if request.GET.get('next',None):
                        return redirect(request.GET.get('next'))
                    # In case the signin route is called without a 'next' GET
                    # parameter set, it automatically redirects to the profile
                    # view
                    return redirect('profile')
                else:
                    logger.error(usr+" was deactivated and rejected for login.")
                    messages.error(request,_("""This user has been deactivated.
                                             Please contact an administrator."""))
            else:
                logger.error(usr +" was not found and rejected for login")
                messages.error(request,_("Incorrect username/password please try again."))

        return render(request, self.template_name, {'form': form})


class SignUp(View):
    form_class = SignUpForm
    template_name = "frontend/signup.html"

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = SignUpForm(request.POST)
        # The signup form was filled in correctly
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            firstname = form.cleaned_data["firstname"]
            lastname = form.cleaned_data["lastname"]
            email = form.cleaned_data["email"]
            idcard = form.cleaned_data["idcard"]
            # Creates a new user and fills in name information
            new_user = User.objects.create_user(username=username, email=email, password=password)
            new_user.first_name = firstname
            new_user.last_name = lastname
            new_user.save()
            # Creates an associated profile and fills in information
            new_profile = UserProfile()
            new_profile.owner = new_user
            new_profile.idcard = idcard
            new_profile.save()
            logger.info("User "+username+" was created successfully. User ID:"+str(new_user.id)+". Profile ID: "+str(new_profile.id))
            messages.success(request,_("You account was created successfully. You can now log in using the chosen username and password."))
            return redirect('signin')

        return render(request, self.template_name, {'form': form })


@login_required()
def profile(request):
    profile = UserProfile.objects.get(owner=request.user)
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        form.instance.owner = request.user
        if form.is_valid():
            form.save()
            logger.info("User "+ request.user.username+" successfully updated his profile.")
            messages.success(request, _("Your profile information has been updated successfully."))
    else:
        form = ProfileUpdateForm(instance=profile)

    return render_to_response("frontend/main_profile.html", {'form': form}, context_instance=RequestContext(request))


def signup(request):
    return render_to_response("frontend/signup.html", { }, )

def reset_password(request):
    form = PasswordResetForm
    if request.method == "POST":
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            user = User.objects.get(username=username)
            new_password = User.objects.make_random_password()
            user.set_password(new_password)
            user.save()
            user.email_user(subject=_("Oblicity App - Password reset"), message="The password for the user "+username+
                            """ associated with this email address has been reset. Your new temporary password is """+ new_password + ". You have 3 days time to change it.")
            logger.info("Password reset for user "+username)
            messages.info(request,_("Password reset successful. We have Emailed you your new temporary password."))

    return render_to_response("frontend/reset_password.html", {'form': form  }, context_instance=RequestContext(request))

def signout(request):
    logger.info("User "+str(request.user)+" successfully logged out")
    logout(request)
    return redirect('signin')



def assets_list(request):
    contracts = Contract.objects.filter(owners__in=[request.user])
    return render_to_response('frontend/assets_list.html', { 'contracts':contracts }, context_instance=RequestContext(request) )

oblicity/templates/frontend/assets_list.html
{% extends 'frontend/main.html' %}
{%  load staticfiles %}
{% load thumbnail %}
{% load i18n %}



<!-- Start: Content -->
  {% block app_content %}
  <section id="content_wrapper">
    <div id="topbar">
      <div class="topbar-left">
            <ol class="breadcrumb">
                <li class="crumb-active"><a href="#">{{ request.user.first_name }}{% trans "'s dashboard" %}</a></li>
                <li class="crumb-trail">{% trans "Assets list" %}</li>
            </ol>
        </div>
    </div>
    <div id="content">
       <div class="row">
        <div class="col-md-12">
          <div class="panel panel-visible">
            <div class="panel-heading">
                <div class="panel-title hidden-xs"> <span class="glyphicon glyphicon-tasks"></span> {% trans "My contracts" %}</div>
            </div>
            <div class="panel-body pbn">

                <a href="{% url "new_contract" %}" class="btn btn-sm bg-purple2" >
                    <span class="fa fa-file-o"></span>
                    {% trans "New Contract" %}
                </a>
                <br><br>
              <table class="table table-striped table-bordered table-hover" id="datatable">
                <thead>
                  <tr>
                      <th>{% trans "Contract name" %}</th>
                      <th class="hidden-xs">{% trans "Owner(s)" %}</th>
                      <th class="visible-lg">{% trans "Validity" %}</th>
                      <th class="visible-lg">{% trans "Last modified (by)" %}</th>
                      <th>{% trans "Status" %}</th>
                      <th class="text-center hidden-xs">{% trans "Actions" %}</th>
                  </tr>
                </thead>
                <tbody>
                    {% for contract in contracts %}
                    <tr data-row-id="{{ contract.id }}">
                            <td>{{ contract.name }}</td>
                            <td class="hidden-xs">
                                {% for owner in contract.owners.all %}
                                {{ owner.first_name }} {{ owner.last_name }}{% if not forloop.last %},{% endif %}
                                {% endfor %}
                            </td>
                            <td class="visible-lg">{{ contract.valid_from }}-{{ contract.valid_to }}</td>
                            <td class="visible-lg">{{ contract.modified }} ({{ contract.last_editor }})</td>
                            <td>{{ contract.get_status_display }}</td>
                            <td class="hidden-xs text-center"><div class="btn-group">
                                <button type="button" onclick="window.location='{% url "edit_contract" id=contract.id %}'" class="btn bg-grey2 btn-gradient btn-sm"> <span class="glyphicons glyphicons-pencil"></span> </button>
                                <button type="button" class="btn bg-purple2 btn-gradient btn-sm" data-action="showPreview" data-target="{{ contract.id }}"> <span class="glyphicon glyphicon-folder-open"></span> </button>
                                <button type="button" class="btn bg-black btn-gradient btn-sm dropdown-toggle" data-toggle="dropdown"> <span class="fa fa-ellipsis-v"></span> </button>
                                <button type="button" class="btn bg-red btn-gradient btn-sm" data-action="deleteConfirm" data-target="{{ contract.id }}" > <span class="glyphicons glyphicons-bin"></span> </button>
                                <ul class="dropdown-menu checkbox-persist pull-right text-left" role="menu">
                                <li><a><i class="fa fa-user"></i> Sign </a></li>
                                <li><a><i class="fa fa-envelope-o"></i> Send to User.. </a></li>
                                <li><a><i class="fa fa-tag"></i> Sign digitally </a></li>
                                <li><a><i class="fa fa-file-text-o"></i> Duplicate </a></li>
                                </ul>
                            </div></td>
                        </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- Modals -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="{% trans "Cancel" %}" ><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="deleteModalLabel">{% trans "Confirm Deletion" %}</h4>
              </div>
              <div class="modal-body">{% trans "Are you sure you want to remove this contract from your assets list? The other existing users will still be able to edit the document, and you will need to be readded as owner by one of them to regain access to this file." %}</div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</button>
                <button type="button" class="btn btn-danger" data-action="delete" data-target="" ><span class="glyphicons glyphicons-bin"></span> {% trans "Delete" %}</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="previewModal" tabindex="-1" role="dialog" aria-labelledby="previewModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="{% trans "Cancel" %}" ><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="previewModalLabel">{% trans "Document preview" %}</h4>
              </div>
              <div class="modal-body"></div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
              </div>
            </div>
          </div>
        </div>

      <!-- /Modals -->
    </div>
  </section>
    {% endblock %}
  <!-- End: Content -->


{% block extrascripts %}
    
    <script type="text/javascript" src={% static "vendor/plugins/datatables/js/jquery.dataTables.min.js" %}></script>
    <script type="text/javascript" src={% static "vendor/plugins/datatables/js/datatables.js" %}></script>
    <script type="text/javascript" src={% static "vendor/plugins/chosen/chosen.jquery.js" %}></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            // Init Datatables with Tabletools Addon
            $('#datatable').dataTable( {
                    "aoColumnDefs": [{ 'bSortable': false, 'aTargets': [ -1 ] }],
                    "oLanguage": { "oPaginate": {"sPrevious": "", "sNext": ""} },
                    "iDisplayLength": 15,
                    "aLengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
                    "sDom": 'T<"panel-menu dt-panelmenu"lfr><"clearfix">tip',
                    "oTableTools": {
                    }
            });

            // Add Placeholder text to datatables filter bar
            $('.dataTables_filter input').attr("placeholder", "Enter Filter Terms Here....");

            // Manually Init Chosen on Datatables Filters
            $("select[name='datatable_length']").chosen();

            // Bind delete modal dialog action
            $("button[data-action='deleteConfirm']").click(function () {
                var button = $("#deleteModal").find("button[data-action='delete']");
                button.data('target',$(this).data('target'));
                $('#deleteModal').modal();
            });
            
            // Bind delete action
            $("button[data-action='delete']").click(function () {
                var url = '{% url "delete_contract" id=0 %}'.replace("0",$(this).data('target'));
                var id = $(this).data('target');
                $.post( url )
                    .done(function(data, textStatus, jqXHR) {
                      $("tr[data-row-id="+id+"]").addClass("animated fadeOutRight");
                    })
                    .fail(function(data, textStatus, jqXHR) {
                    })
                $('#deleteModal').modal('hide');
            });

            // Bind preview action
            $("button[data-action='showPreview']").click(function () {
                var url = '{% url "get_contract_body" id=0 %}'.replace("0",$(this).data('target'));
                var id = $(this).data('target');
                $.get( url )
                    .done(function(data, textStatus, jqXHR) {
                        $("#previewModal").find(".modal-body").html(data);
                        $("#previewModal").modal();
                    })
                    .fail(function(data, textStatus, jqXHR) {
                        alert(data.responseText);
                    })
            });


        });
    </script>

{% endblock %}

oblicity/templates/frontend/footer.html
<div class="fixed-footer">
   <?PHP include('footer_notes.php'); ?>
</div>

oblicity/templates/frontend/main.html
{% extends "frontend/base.html" %}
{%  load staticfiles %}
{% load thumbnail %}
{% load i18n %}


{% block body %}
<body>
<!-- Start: Header -->
{% include "frontend/topbar.html" %}
<!-- End: Header --> 
<!-- Start: Main -->
<div id="main"> 
  <!-- Start: Sidebar -->
  {% include "frontend/sidebar.html" %}
  <!-- End: Sidebar -->
  <!-- Start: Content -->
  {% block app_content %}
    {% endblock %}
  <!-- End: Content --> 
  
  <!-- Start: Right Sidebar -->
  {% include "frontend/sidebar_right.html" %}
  <!-- End: Right Sidebar --> 
</div>
<!-- End: Main --> 
</body>

<!-- End: Main -->
{% endblock %}

oblicity/templates/frontend/main_profile.html
{% extends 'frontend/main.html' %}
{%  load staticfiles %}
{% load thumbnail %}
{% load i18n %}



<!-- Start: Content -->
  {% block app_content %}
    <section id="content_wrapper">
        <div id="topbar">
        <div class="topbar-left">
            <ol class="breadcrumb">
                <li class="crumb-active"><a href="#">{{ request.user.first_name }}{% trans "'s dashboard" %}</a></li>
            <li class="crumb-icon"><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
            <li class="crumb-trail">{% trans "Profile" %}</li>
            </ol>
        </div>
        </div>
        <div id="content" class="prn">
            <div class="row">
                <div class="col-md-3 pl25 pr25 ">
                    <h5 class="text-muted"> {% trans "Account" %} </h5>
                <hr class="short">
                <p>{% trans "This is your main profile page. When you keep your profile updated, you are helping other users get to know who you are. Remember that your tag line will be public." %}</p>
                <h5 class="mt30 text-muted"> Statistics </h5>
                <hr class="short">
                <p class="fs12 text-muted"> <span class="glyphicons glyphicons-user mr10 text-purple"></span> 122 Connections</p>
                <p class="fs12 text-muted"> <span class="glyphicons glyphicons-user_add mr10 text-orange"></span> 3 Requests</p>
                <p class="fs12 text-muted"> <span class="glyphicons glyphicons-star mr10 text-blue2"></span> 74 Contracts </p>
                <h5 class="mt30 text-muted"> Purchased Bundles </h5>
                <hr class="short">
                <p class="mb5"><span class="label bg-purple mr10">Commercial</span><span class="label bg-purple mr10">Rent</span><span class="label bg-purple mr10">Filings</span><span class="label bg-purple mr10">Loans</span><span class="label bg-purple mr10">Proceedings</span></p>
                <p><span class="label bg-purple mr10">Divorces</span><span class="label bg-purple mr10">Testaments</span><span class="label bg-purple mr10">Extras</span></p>
                </div>
                <div class="col-md-8 profile-tabs pl25">
                <div class="tab-block">
                    <ul class="nav nav-tabs">
                    <li class="active"><a href="#profile1" data-toggle="tab"> Edit Profile</a></li>
                    <li><a href="#profile2" data-toggle="tab">Notifications</a></li>
                    </ul>
                    <div class="tab-content border-right-none pn">
                    <div id="profile1" class="tab-pane p30 active">
                        <div class="row">
                        <div class="col-sm-5 pr15">
                            <h5 class="text-muted"> {% trans "Basic Information" %} </h5>
                            <hr class="short mb35"/>
                            <form action="{% url "profile" %}" id="profileForm" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-old_man"></span> </span>
                                <input class="form-control" type="text" value="{{ request.user.username }} " disabled="disabled">
                            </div>
                            </div>
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-credit_card"></span> </span>
                                {{ form.idcard }}
                            </div>
                            </div>
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-message_flag"></span> </span>
                                <input class="form-control" type="text" value="{{ request.user.email }}", disabled="disabled">
                            </div>
                            </div>
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-gift"></span> </span>
                                {{ form.birth }}
                            </div>
                                {{ form.birth.errors }}
                            </div>
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-home"></span> </span>
                                {{ form.address }}
                            </div>
                                {{ form.address.errors }}
                            </div>
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-book_open"></span> </span>
                                {{ form.profession }}
                            </div>
                                {{ form.profession.errors }}
                            </div>
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-phone"></span> </span>
                                {{ form.phone }}
                            </div>
                                {{ form.phone.errors }}
                            </div>
                            <div class="form-group">
                            <div class="input-group mb10"> <span class="input-group-addon"><span class="glyphicons glyphicons-globe"></span> </span>
                                {{ form.website }}
                            </div>
                                {{ form.website.errors }}
                            </div>
                        </div>
                        <div class="col-sm-5 pl15">
                            <h5 class="text-muted"> {% trans "Profile Picture" %} </h5>
                            <hr class="short mb35"/>
                            {% thumbnail form.instance.picture "250x250" crop="center" as im %}
                            <img class="img-responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" /><br>
                            {% endthumbnail %}
                                {{ form.picture }} 
                                <br> <p class="text-purple2"><span class="glyphicons glyphicons-user mr10"></span>Please tell other users about yourself.</p>
                            <div class="form-group mb20">
                                {{ form.description }}
                            </div>
                            <button class="btn bg-purple2 btn-lg pull-right" type="submit">{% trans "Update Profile" %}</button>
                        </form>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
            </section>
    {% endblock %}
  <!-- End: Content -->


{% block extrascripts %}
    <script type="text/javascript">
        jQuery(document).ready(function () {
            $('#id_birth').datepicker();
        });
    </script>

{% endblock %}

oblicity/templates/frontend/reset_password.html
{% extends "frontend/base.html" %}
{%  load staticfiles %}
{% load thumbnail %}
{% load i18n %}


{% block body %}
<body class="minimal login-page">

<!-- Start: Main -->
<div id="main">
  <div id="content">
    <div class="row">
        <div id="page-logo"> <img src={% static "img/logos/logo-white.png" %} class="img-responsive" alt="logo"> </div>
    </div>
    <div class="row">
      <div class="panel-bg animated {% if form.errors %} shake{% endif %}">
        <form action="{% url "resetpass" %}" method="POST" id="resetpasswordForm">{% csrf_token %}
        <div class="panel">
            <div class="panel-heading"> <span class="panel-title"> <span class="fa fa-lock text-purple2"></span> {% trans "Password reset " %}</span> </div>
            <div class="panel-body">
                <p>{% trans "This procedure allows you to reset the password for your account. You must provide both your username and associated Email address." %}</p>
                <p>{% trans "On successful password reset, we will send you an Email with the new password, which must be changed within 3 days." %}</p>
                <div class="alert alert-error" role="alert">{{ form.non_field_errors }}</div>
                    <div class="form-group">
                        <div class="input-group"> <span class="input-group-addon">{% trans "Username" %} </span>
                            {{ form.username }}
                        </div>
                        {{ form.username.errors }}
                    </div>
                    <div class="form-group">
                        <div class="input-group"> <span class="input-group-addon">{% trans "Email address" %} </span>
                            {{ form.email }}
                        </div>
                        {{ form.email.errors }} 
                    </div>
            </div>
          <div class="panel-footer">
              <a class="btn btn-sm bg-purple2 pull-right" onclick="$('#resetpasswordForm').submit()" href="#">{% trans "Reset password" %}</a>
              
              <input type="submit" style="display:none;">
            <span class="text-muted fs12">
                <a href="{% url "signin" %}"> {% trans "Go back" %}</a>
            </span>
            <div class="clearfix"></div>
          </div>
        </div>
      </form>
      </div>
    </div>
  </div>
</div>
{% include "frontend/footer.html" %}
<div class="overlay-black"></div>

</body>
{% endblock %}